version: "3.4"
services:

  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:jammy
    network_mode: host
    command: sleep infinity
  
  browserless:
    image: ghcr.io/browserless/chrome:latest
    network_mode: service:devcontainer
    environment:
      CONCURRENT: 10
      TOKEN: null
    restart: always

  umami:
    image: docker.umami.dev/umami-software/umami:postgresql-latest
    ports:
      - 8079:3000
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/umami
    restart: always

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: umami
      POSTGRES_PASSWORD: password
    restart: always
